### ISSUE TITLE
Usage w/out coldbox

### ISSUE THREAD

**Issue by artknight** [akitogo/GoogleCloudTranslation#1]
Hi,
I am wondering if there is a way to use it without using the coldbox?

**Comment by GunnarLieb** [comment]
Sure, it's just copy the GoogleTranslation.cfc from the models folder anywhere you want. 

You can use it with ggl= createObject("component","GoogleTranslation").init(YOUR_APIKEY_HERE);

For examples see: https://github.com/akitogo/GoogleCloudTranslation#usage

If you are looking for translation you should check: https://github.com/akitogo/cbDeepl which delivers much better results than Google
